import {Colors, Constant} from 'global/Index';
import {Platform, StyleSheet} from 'react-native';
import {width} from '../../../global/Constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  mainView: {
    padding: 20,
  },
  reviewProcessContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  reviewProcessTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  arrowView: {
    backgroundColor: Colors.LIGHT_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
    height: 20,
    width: 20,
    borderRadius: 6,
  },
  estimateContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    paddingVertical: 15,
    paddingHorizontal: 10,
    marginRight: 20,
    width: width * 0.75,
  },
  estimateTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  estimateBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  resultsView: {
    backgroundColor: Colors.LIGHT_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
  },
  longText: {
    color: Colors.LIGHT_GRAY,
    fontSize: 14,
    lineHeight: 20,
    width: '90%',
  },
  priceContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    padding: 10,
    paddingVertical: 15,
    // paddingHorizontal: 10,
    marginRight: 10,
    width: width * 0.88,
  },
  priceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceMiddleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    height: 20
  },
  priceBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    // marginHorizontal: 10,
    borderRadius: 4,
    paddingTop: 5,
    paddingBottom: 8,
  },
  logoView: {
    // backgroundColor: '#FBFBFB',
    justifyContent: 'center',
    alignItems: 'center',
    height: 63,
    width: 63,
    borderRadius: 10,
  },
  programViewAll: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    marginBottom: 15,
  },
  webViewContainer: {
    width: width - 40,
    height: 219,
    borderRadius: 10,
    overflow: 'hidden',
  },
  webViewStyle: {
    width: width - 40,
    height: 219,
    opacity: 0.99,
  },
  instantQuoteContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  homebg: {
    width: '100%',
    height: 247,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 10,
  },
  buttonStyle: {
    marginTop: 10,
    alignSelf: 'center',
    width: '100%',
    height: 60,
  },
});
