import {Colors, Constant} from 'global/Index';
import {Platform, StyleSheet} from 'react-native';
import {height, width} from '../../../global/Constant';

export const styles = StyleSheet.create({
  container: {
   // flex: 1,
    // backgroundColor: '#0C8AFF83',
  },
  mainView: {
    padding: 20,
    marginTop: -120,
  },
  homebg: {
    width: width,
    height: 247,
    // marginTop: -7,
  },
  profileDetailsContainer: {
    backgroundColor: 'white',
    width: width * 0.9,
    borderRadius: 10,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
    // alignItems: 'center',
    shadowColor: Colors.THEME_GRAY,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
  },
  buttonStyle: {
    marginTop: 10,
    // marginBottom: 15,
    width: '90%',
    height: 54,
  },
  img: {
    height: 110,
    width: 110,
    borderRadius: 110 / 2,
    borderWidth: 2,
    borderColor: 'white',
    marginTop: -50,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'center',
    marginBottom: 5,
  },
  editView: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    borderColor: Colors.THEME_BLUE,
    borderWidth: 2,
    top: 30,
    right: 30,
  },
  moneyContainer: {
    backgroundColor: 'white',
    width: width * 0.9,
    borderRadius: 10,
    overflow: 'hidden',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 20,
    // paddingHorizontal: 10,
    shadowColor: Colors.THEME_GRAY,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
  },
  starRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
  },
  infoView: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.THEME_BLUE,
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
  },
  redeemedContainer: {
    backgroundColor: 'white',
    width: width * 0.9,
    borderRadius: 10,
    overflow: 'hidden',
    // alignSelf: 'center',
    // alignItems: 'center',
    marginTop: 20,
    paddingVertical: 20,
    paddingHorizontal: 10,
    shadowColor: Colors.THEME_GRAY,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
  },
  ownerContainer: {
    backgroundColor: 'white',
    width: width * 0.9,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    shadowColor: Colors.THEME_GRAY,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pointContainer: {
    marginLeft: 20,
    alignSelf: 'flex-start',
    marginTop: 20,
    marginBottom: 5,
  },
  tickView: {
    backgroundColor: 'rgba(12, 138, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
  },
  pointRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 15,
  },
  logo: {
    alignSelf: 'center',
    marginTop: 20,
    height: 145,
    width: 145,
  },
  logoContainer: {
    backgroundColor: '#FBFBFB',
    justifyContent: 'center',
    alignItems: 'center',
    height: 65,
    width: 111,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.BRIGHT_GRAY,
    position: 'absolute',
    zIndex: 1,
  },
  logoView: {
    backgroundColor: '#FBFBFB',
    justifyContent: 'center',
    alignItems: 'center',
    height: 53,
    width: 73,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.BRIGHT_GRAY,
  },
  contractTab: {
    backgroundColor: Colors.BRIGHT_GRAY,
    borderRadius: 10,
    height: 209,
    width: 309,
    marginRight: 20,
  },
  contractContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    padding: 10,
    // paddingHorizontal: 10,
    marginRight: 20,
    // width: width * 0.8,
    height: 167,
    width: 309,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  container2: { flex: 1, padding: 16, paddingTop: 30, backgroundColor: '#fff' },
  header: { height: 50, backgroundColor: '#537791' },
  text: { textAlign: 'center', fontWeight: '100' },
  dataWrapper: { marginTop: -1 },
  row: { height: 40, backgroundColor: '#E7E6E1' },
  mybutton:{
    // flexDirection:'row',
  backgroundColor: 'white',
width: width * 0.9,
borderRadius: 10,
overflow: 'hidden',
alignSelf: 'center',
// alignItems: 'center',
marginTop: 20,
padding:10,
height:50,
// paddingTop: 20,
// paddingHorizontal: 10,
shadowColor: Colors.THEME_GRAY,
shadowOffset: {width: 0, height: 2},
shadowOpacity: 0.05,
shadowRadius: 15,
elevation: 2,}
});
