import {Colors} from 'global/Index';
import {StyleSheet} from 'react-native';
import {width} from '../../../global/Constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FBFBFB',
  },
  mainView: {
    paddingHorizontal: 20,
    backgroundColor:'#F3EFEE',
    flex:1
  },
  bannerImage: {zIndex:5},
  image: {width: '100%', height: 400,marginTop:-50},
  headerText: {
    fontSize: 24,
    fontWeight: '500',
    color: Colors.THEME_BLUE,
    
  },
  subheaderText: {fontSize: 24, fontWeight: '400', color: Colors.LIGHT_BLUE},
  subSubHeaderText: {fontSize: 16, fontWeight: '400', color: Colors.LIGHT_GRAY},
  descriptionContainer: {marginTop: 5},
  descriptionText: {
    textAlign: 'justify',
    fontSize: 14,
    fontWeight: '400',
    color: Colors.THEME_GRAY,
  },
  midImage: {
    height: 180,
    width: 350,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: '#E7F3FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  midImageNotFilled: {
    height: 180,
    width: 350,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: '#E7F3FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  textInput: {
    padding: 10,
    paddingLeft: 20,
    width: '49%',
    height: 50,
    // color: '#455A64',
    color: Colors.THEME_GRAY,
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#E0E0E0',
    backgroundColor: Colors.WHITE,
  },
  textInputNotFilled: {
    padding: 10,
    paddingLeft: 20,
    width: '49%',
    height: 50,
    // color: '#455A64',
    color: Colors.THEME_GRAY,
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.RED,
    backgroundColor: Colors.WHITE,
  },
  textInput2: {
    padding: 10,
    paddingLeft: 20,
    width: '32%',
    height: 50,
    // color: '#455A64',
    color: Colors.THEME_GRAY,
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#E0E0E0',
    backgroundColor: Colors.WHITE,
  },
  textInput2NotFilled: {
    padding: 10,
    paddingLeft: 20,
    width: '32%',
    height: 50,
    // color: '#455A64',
    color: Colors.THEME_GRAY,
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.RED,
    backgroundColor: Colors.WHITE,
  },
  signText: {
    textAlign: 'justify',
    fontSize: 14,
    fontWeight: '400',
    color: Colors.BLACK,
  },
  addressText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '400',
    color: Colors.LIGHT_GRAY,
    paddingVertical: 3,
  },
  bottomLogo: {
    height: 110,
    width: 110,
    borderRadius: 50,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 10,
  },
  loginStyle: {
    marginTop: 10,
    marginBottom: 10,
    alignSelf: 'center',
    width: '100%',
  },
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  selectedPaymentMethodView: {
    borderRadius: 10,
    borderColor: '#4A95CF',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E7F3FF',
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  unselectedPaymentMethodView: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  imageViewStyle: {
    width: 110,
    height: 110,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonStyle: {
    position: 'absolute',
    backgroundColor: Colors.WHITE,
    borderRadius: 100,
    padding: 5,
    right: 5,
    top: 5,
  },
  addButtonStyle: {
    backgroundColor: Colors.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
  },
  redBorderNotFilled: {
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  agremntBtwnFilledStyle: {
    marginVertical: 10,
  },
  agremntBtwnNotFilledStyle: {
    marginVertical: 10,
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  withinDaysFilledStyle: {
    marginVertical: 10,
  },
  withinDaysNotFilledStyle: {
    marginVertical: 10,
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  rentOutFilledStyle: {
    marginVertical: 10,
  },
  rentOutNotFilledStyle: {
    marginVertical: 10,
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  genericInputFilledStyle: {
    marginVertical: 10,
  },
  genericInputNotFilledStyle: {
    marginVertical: 10,
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  dateSelectorFilledStyle: {
    width: '100%',
  },
  dateSelectorNotFilledStyle: {
    width: '100%',
    borderColor: Colors.RED,
    borderWidth: 1,
  },
  tickView: {
    backgroundColor: 'rgba(12, 138, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
  },
  inputContainer: {
    width:'70%',
    marginLeft:22,
    marginBottom:10
  },
  textInput: {
    borderBottomWidth: 0.5, // Set the bottom border width
    borderBottomColor: 'black', // Set the bottom border color
    fontSize: 14,
    height: 20,
  },
});
