import {Colors, Constant} from 'global/Index';
import {Platform, StyleSheet} from 'react-native';
import {height, width} from '../../../global/Constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  mainView: {
    padding: 20,
    marginTop: 40,
  },
  screenLogo: {
    width: 108,
    height: 108,
    position: 'absolute',
    zIndex: 1,
    left: 33,
    top: 140,
  },
  homebg: {
    width: width,
    height: 195,
    marginTop: -5,
  },
  contractTab: {
    backgroundColor: Colors.BRIGHT_GRAY,
    borderRadius: 10,
    height: 209,
    width: 309,
    marginRight: 20,
  },
  contractContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: Colors.THEME_BLUE,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
    padding: 10,
    // paddingHorizontal: 10,
    marginRight: 20,
    // width: width * 0.8,
    height: 167,
    width: 309,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoContainer: {
    backgroundColor: '#FBFBFB',
    justifyContent: 'center',
    alignItems: 'center',
    height: 65,
    width: 111,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.BRIGHT_GRAY,
    position: 'absolute',
    zIndex: 1,
  },
  logoView: {
    backgroundColor: '#FBFBFB',
    justifyContent: 'center',
    alignItems: 'center',
    height: 53,
    width: 73,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.BRIGHT_GRAY,
  },
  buttonStyle: {
    marginTop: 10,
    // marginBottom: 15,
    alignSelf: 'center',
    // width: '100%',
    width: width * 0.36,
    height: 44,
  },
  pdfImg: {
    width: 66,
    height: 51,
    marginTop: 90,
  },
  sgImg: {
    borderRadius: 10,
    width: 178,
    height: 145,
    // marginLeft: 100,
  },
  rightArrowContainer: {
    width: 29,
    height: 27,
    borderRadius: 50,
    backgroundColor: Colors.THEME_BLUE,
    marginLeft: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightArrowIcon: {
    width: 15,
    height: 17,
  },
});
