require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.1'
install! 'cocoapods', :deterministic_uuids => false
#use_modular_headers!
#use_frameworks! :linkage => :static
target 'TimeSharing' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()

      pod 'Firebase', :modular_headers => true
      pod 'FirebaseCore', :modular_headers => true
      pod 'FirebaseCoreInternal', :modular_headers => true
      pod 'FirebaseCoreExtension', :modular_headers => true
      pod 'FirebaseMessagingInterop', :modular_headers => true
      pod 'GTMSessionFetcher', :modular_headers => true
      pod 'FirebaseAppCheckInterop', :modular_headers => true
      pod 'FirebaseAuthInterop', :modular_headers => true
      pod 'GoogleUtilities', :modular_headers => true
      $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TimeSharingTests' do
    inherit! :complete
  end
#  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
       __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

